version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: app
    volumes:
      - ./:/app
    ports:
      - "3000:3000" # Map appropriate ports
    restart: always
