version: '3.8'

services:
  db:  
    image: mongo:7.0.16-jammy
    restart: always
    environment:
      MONGO_INITDB_DATABASE: wishlist
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - "27017:27017" 
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000" 
    depends_on:
      - db
    restart: always