# Stage: Development Environment
FROM node:23-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install
COPY prisma ./prisma/
RUN npx prisma generate
RUN npm install @prisma/client
# Expose the development server port
EXPOSE 3000

# Start the Next.js app in development mode with hot reload
CMD ["sh", "/app/start.sh"]